//! Port of `sdk/include/FidelityFX/gpu/fsr2/ffx_fsr2_resources.h` (FidelityFX SDK 1.1.4).
pub const FFX_FSR2_RESOURCE_IDENTIFIER_NULL: u32 = 0;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INPUT_OPAQUE_ONLY: u32 = 1;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INPUT_COLOR: u32 = 2;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INPUT_MOTION_VECTORS: u32 = 3;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INPUT_DEPTH: u32 = 4;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INPUT_EXPOSURE: u32 = 5;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INPUT_REACTIVE_MASK: u32 = 6;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INPUT_TRANSPARENCY_AND_COMPOSITION_MASK: u32 = 7;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_RECONSTRUCTED_PREVIOUS_NEAREST_DEPTH: u32 = 8;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_DILATED_MOTION_VECTORS: u32 = 9;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_DILATED_DEPTH: u32 = 10;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INTERNAL_UPSCALED_COLOR: u32 = 11;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_LOCK_STATUS: u32 = 12;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_NEW_LOCKS: u32 = 13;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_PREPARED_INPUT_COLOR: u32 = 14;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_LUMA_HISTORY: u32 = 15;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_DEBUG_OUTPUT: u32 = 16;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_LANCZOS_LUT: u32 = 17;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SPD_ATOMIC_COUNT: u32 = 18;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_UPSCALED_OUTPUT: u32 = 19;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_RCAS_INPUT: u32 = 20;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_LOCK_STATUS_1: u32 = 21;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_LOCK_STATUS_2: u32 = 22;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INTERNAL_UPSCALED_COLOR_1: u32 = 23;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INTERNAL_UPSCALED_COLOR_2: u32 = 24;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INTERNAL_DEFAULT_REACTIVITY: u32 = 25;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INTERNAL_DEFAULT_TRANSPARENCY_AND_COMPOSITION: u32 = 26;
pub const FFX_FSR2_RESOURCE_IDENTITIER_UPSAMPLE_MAXIMUM_BIAS_LUT: u32 = 27;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_DILATED_REACTIVE_MASKS: u32 = 28;
/// same as FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_0
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE: u32 = 29;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_0: u32 = 29;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_1: u32 = 30;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_2: u32 = 31;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_3: u32 = 32;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_4: u32 = 33;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_5: u32 = 34;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_6: u32 = 35;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_7: u32 = 36;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_8: u32 = 37;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_9: u32 = 38;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_10: u32 = 39;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_11: u32 = 40;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_12: u32 = 41;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INTERNAL_DEFAULT_EXPOSURE: u32 = 42;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_AUTO_EXPOSURE: u32 = 43;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_AUTOREACTIVE: u32 = 44;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_AUTOCOMPOSITION: u32 = 45;

pub const FFX_FSR2_RESOURCE_IDENTIFIER_PREV_PRE_ALPHA_COLOR: u32 = 46;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_PREV_POST_ALPHA_COLOR: u32 = 47;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_PREV_PRE_ALPHA_COLOR_1: u32 = 48;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_PREV_POST_ALPHA_COLOR_1: u32 = 49;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_PREV_PRE_ALPHA_COLOR_2: u32 = 50;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_PREV_POST_ALPHA_COLOR_2: u32 = 51;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_PREVIOUS_DILATED_MOTION_VECTORS: u32 = 52;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INTERNAL_DILATED_MOTION_VECTORS_1: u32 = 53;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_INTERNAL_DILATED_MOTION_VECTORS_2: u32 = 54;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_LUMA_HISTORY_1: u32 = 55;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_LUMA_HISTORY_2: u32 = 56;
pub const FFX_FSR2_RESOURCE_IDENTIFIER_LOCK_INPUT_LUMA: u32 = 57;

/// Shading change detection mip level setting, value must be in the range [FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_0, FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_12]
pub const FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_SHADING_CHANGE: u32 =
    FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_4;
pub const FFX_FSR2_SHADING_CHANGE_MIP_LEVEL: u32 =
    FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE_MIPMAP_SHADING_CHANGE
        - FFX_FSR2_RESOURCE_IDENTIFIER_SCENE_LUMINANCE;

pub const FFX_FSR2_RESOURCE_IDENTIFIER_COUNT: u32 = 58;

pub const FFX_FSR2_CONSTANTBUFFER_IDENTIFIER_FSR2: u32 = 0;
pub const FFX_FSR2_CONSTANTBUFFER_IDENTIFIER_SPD: u32 = 1;
pub const FFX_FSR2_CONSTANTBUFFER_IDENTIFIER_RCAS: u32 = 2;
pub const FFX_FSR2_CONSTANTBUFFER_IDENTIFIER_GENREACTIVE: u32 = 3;

pub const FFX_FSR2_AUTOREACTIVEFLAGS_APPLY_TONEMAP: u32 = 1;
pub const FFX_FSR2_AUTOREACTIVEFLAGS_APPLY_INVERSETONEMAP: u32 = 2;
pub const FFX_FSR2_AUTOREACTIVEFLAGS_APPLY_THRESHOLD: u32 = 4;
pub const FFX_FSR2_AUTOREACTIVEFLAGS_USE_COMPONENTS_MAX: u32 = 8;
